import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const generateScentPDF = async (scent: any, strength: string): Promise<void> => {
  try {
    // Create a temporary div with the scent card content
    const tempDiv = document.createElement('div');
    tempDiv.style.position = 'absolute';
    tempDiv.style.left = '-9999px';
    tempDiv.style.width = '800px';
    tempDiv.style.backgroundColor = 'white';
    tempDiv.style.padding = '40px';
    tempDiv.style.fontFamily = 'Arial, sans-serif';
    
    tempDiv.innerHTML = `
      <div style="text-align: center; margin-bottom: 30px;">
        <h1 style="color: #7c3aed; font-size: 32px; margin-bottom: 10px;">${scent.name}</h1>
        <p style="color: #6b7280; font-size: 16px;">Generated by AI Scent Lab</p>
        <div style="margin: 20px 0;">
          <span style="color: #374151; font-weight: bold;">Scent Strength: </span>
          <span style="color: #7c3aed; font-weight: bold;">${strength}</span>
        </div>
      </div>

      <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 20px; margin-bottom: 30px;">
        <div style="background: #dbeafe; padding: 20px; border-radius: 12px;">
          <h3 style="color: #1e40af; margin-bottom: 15px; font-size: 18px;">🌊 Top Notes</h3>
          ${scent.topNotes.map((note: string) => `<div style="background: #bfdbfe; padding: 8px 12px; margin: 5px 0; border-radius: 8px; color: #1e40af;">${note}</div>`).join('')}
        </div>
        
        <div style="background: #dcfce7; padding: 20px; border-radius: 12px;">
          <h3 style="color: #166534; margin-bottom: 15px; font-size: 18px;">🌿 Middle Notes</h3>
          ${scent.middleNotes.map((note: string) => `<div style="background: #bbf7d0; padding: 8px 12px; margin: 5px 0; border-radius: 8px; color: #166534;">${note}</div>`).join('')}
        </div>
        
        <div style="background: #fef3c7; padding: 20px; border-radius: 12px;">
          <h3 style="color: #92400e; margin-bottom: 15px; font-size: 18px;">🌳 Base Notes</h3>
          ${scent.baseNotes.map((note: string) => `<div style="background: #fde68a; padding: 8px 12px; margin: 5px 0; border-radius: 8px; color: #92400e;">${note}</div>`).join('')}
        </div>
      </div>

      <div style="margin-bottom: 30px;">
        <h3 style="color: #374151; margin-bottom: 15px; font-size: 20px;">🧪 Key Ingredients</h3>
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px;">
          ${scent.ingredients.map((ingredient: any) => `
            <div style="background: #f9fafb; padding: 15px; border-radius: 8px; display: flex; justify-content: space-between; border: 1px solid #e5e7eb;">
              <span style="color: #374151; font-weight: 500;">${ingredient.name}</span>
              <span style="color: #7c3aed; font-weight: bold;">${ingredient.percentage}</span>
            </div>
          `).join('')}
        </div>
      </div>

      <div style="background: linear-gradient(135deg, #f3e8ff, #fce7f3); padding: 25px; border-radius: 12px;">
        <h3 style="color: #374151; margin-bottom: 15px; font-size: 20px;">✨ Fragrance Profile</h3>
        <p style="color: #4b5563; line-height: 1.6; font-size: 16px;">${scent.description}</p>
      </div>

      <div style="text-align: center; margin-top: 30px; padding-top: 20px; border-top: 2px solid #e5e7eb;">
        <p style="color: #9ca3af; font-size: 14px;">Created on ${new Date().toLocaleDateString()}</p>
        <p style="color: #9ca3af; font-size: 12px;">AI Scent Lab - Your Personal Fragrance Designer</p>
      </div>
    `;

    document.body.appendChild(tempDiv);

    // Convert to canvas
    const canvas = await html2canvas(tempDiv, {
      backgroundColor: '#ffffff',
      scale: 2,
      useCORS: true,
      allowTaint: true
    });

    // Remove temporary div
    document.body.removeChild(tempDiv);

    // Create PDF
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    
    const imgWidth = 210; // A4 width in mm
    const pageHeight = 295; // A4 height in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = 0;

    // Add first page
    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    // Add additional pages if needed
    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    // Save the PDF
    const fileName = `${scent.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_scent_formula.pdf`;
    pdf.save(fileName);

  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error('Failed to generate PDF');
  }
};

export const generateScentImage = async (scent: any, strength: string): Promise<string> => {
  try {
    // Create a temporary div for image generation
    const tempDiv = document.createElement('div');
    tempDiv.style.position = 'absolute';
    tempDiv.style.left = '-9999px';
    tempDiv.style.width = '600px';
    tempDiv.style.backgroundColor = 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)';
    tempDiv.style.padding = '40px';
    tempDiv.style.borderRadius = '20px';
    tempDiv.style.color = 'white';
    tempDiv.style.fontFamily = 'Arial, sans-serif';
    
    tempDiv.innerHTML = `
      <div style="text-align: center;">
        <h1 style="font-size: 28px; margin-bottom: 20px; text-shadow: 2px 2px 4px rgba(0,0,0,0.3);">${scent.name}</h1>
        <div style="background: rgba(255,255,255,0.2); padding: 20px; border-radius: 15px; margin-bottom: 20px;">
          <p style="font-size: 16px; line-height: 1.5; margin: 0;">${scent.description}</p>
        </div>
        <div style="display: flex; justify-content: space-around; margin-bottom: 20px;">
          <div style="text-align: center;">
            <div style="font-size: 14px; opacity: 0.8;">Top Notes</div>
            <div style="font-weight: bold;">${scent.topNotes.slice(0, 2).join(', ')}</div>
          </div>
          <div style="text-align: center;">
            <div style="font-size: 14px; opacity: 0.8;">Heart Notes</div>
            <div style="font-weight: bold;">${scent.middleNotes.slice(0, 2).join(', ')}</div>
          </div>
          <div style="text-align: center;">
            <div style="font-size: 14px; opacity: 0.8;">Base Notes</div>
            <div style="font-weight: bold;">${scent.baseNotes.slice(0, 2).join(', ')}</div>
          </div>
        </div>
        <div style="font-size: 14px; opacity: 0.9;">Created with AI Scent Lab</div>
      </div>
    `;

    document.body.appendChild(tempDiv);

    const canvas = await html2canvas(tempDiv, {
      backgroundColor: null,
      scale: 2
    });

    document.body.removeChild(tempDiv);

    return canvas.toDataURL('image/png');
  } catch (error) {
    console.error('Error generating image:', error);
    throw new Error('Failed to generate image');
  }
};